### PR TITLE
Basic networking

### PR DESCRIPTION
**Pull request by HonestJoe**

### CODE REVIEW

**Comment by lucaswalter** [comment]
Still working on the UDP connection for this. It looks like this is all the code I have worked on. Do you have a branch with the account login functionality?

**Comment by lucaswalter** [comment]
Async message callback successfully implemented. The next step will be to encode & decode our JSON messages.

**Comment by HonestJoe** [comment]
Sorry, still kind of figuring out how to use Git. I pushed to my master, had to force it. Might be cool if you could show me how to push to the right branches.

**Comment by HonestJoe** [comment]
To clarify, the merge was just me trying to clone the right version. Kind of derping it up.

**Comment by lucaswalter** [comment]
I would recommend forking the repository to your own account. Changes should not be made to the master branch until we hit milestones. The branch structure should go: master > develop > individual feature.

**Comment by HonestJoe** [comment]
Well, it's my forked master. I couldn't seem to pull the other ones.

**Comment by lucaswalter** [comment]
Once the changes are made and tested to be working inside of your individual feature branch, you can submit a pull request to develop using this repository as a remote.

**Comment by HonestJoe** [comment]
Well, once I figure out how to do that, that will be great.

**Comment by lucaswalter** [comment]
If the repository is forked/cloned the develop branch should exist. Try downloading the github desktop app. They have an awesome UI that makes switching branches very easy.

**Comment by lucaswalter** [comment]
Don't worry about it tonight. I can walk everyone through it tomorrow after the code review if you would like. Just bring a laptop or make sure the code you wrote will be able to be presented on.

**Comment by HonestJoe** [comment]
I'll probably end up doing that. I know that my code was pushed to my fork, so we can pull it up.

**Comment by HonestJoe** [comment]
Well, see you in class. I'm getting some sleep.

**Comment by lucaswalter** [comment]
Sound Good!

**Pull request merged**
